services:
    werkint.redis.service:
        class: Werkint\Bundle\RedisBundle\Service\Redis
        arguments:
            - %werkint_redis_connection%
    werkint.redis.provider:
        class:    Werkint\Bundle\RedisBundle\Service\RedisCache
        abstract: true
    werkint.redis.session:
        class: Werkint\Bundle\RedisBundle\Service\RedisSessionHandler
        arguments:
            - @werkint.redis.service
            - { cookie_lifetime: %werkint_redis_session_expire% }
            - %werkint_redis_session_prefix%
    werkint.redis.doctrinecacher:
        class: Werkint\Bundle\RedisBundle\Service\DoctrineCacher
        tags:
            - { name: werkint.redis.cacheservice, ns: werkint.doctrine }