services:
    werkint.redis.service:
        class: Werkint\Bundle\RedisBundle\Service\Memcached
        arguments:
            - %werkint_memcached_host%
            - %werkint_memcached_port%
    werkint.redis.provider:
        class:    Doctrine\Common\Cache\MemcachedCache
        abstract: true
    werkint.redis.session:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments:
            - @werkint.memcached.service
            - { prefix: %werkint_memcached_session_prefix%, expiretime: %werkint_memcached_session_expire% }