services:
    werkint.redis.service:
        class: Werkint\Bundle\RedisBundle\Service\Redis
        arguments:
            - %werkint_redis_connection%
    werkint.redis.provider:
        class: Werkint\Bundle\RedisBundle\Service\RedisCache
        abstract: true
    werkint.redis.session:
        class: Werkint\Bundle\RedisBundle\Service\RedisSessionHandler
        arguments:
            - @werkint.redis.service
            - @=parameter('session.storage.options')
            - @=parameter('werkint_redis')['session']['prefix']
    werkint.redis.doctrinecacher:
        class: Werkint\Bundle\RedisBundle\Service\DoctrineCacher
        parent: werkint.redis.provider
        tags:
            - { name: werkint.redis.cacheservice, ns: werkint.doctrine }